### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by zimt28** [CodeAdventure/space-ui#10]
I want to insert a document and then use its callback to pass the returned id to a method. How and where would I do that? Does the dispatcher support callbacks and is that intended?

**Comment by zimt28** [comment]
I have more questions on this :) I have this simple line of code, which is part of my store.
```coffeescript
  # Insert a new case into db
  _createCase: (data) ->
    @cases.insert data, (err, res) ->
      console.log err or res
```
I'd now like to open a notification on error or response. However, the store seems to be the wrong place to do it. I've just used collection-hooks to handle the successful insert using `@cases.after.insert`, but can't handle failing inserts. I think it might be good to put the code for the alerts into my mediator - is there a way to call functions on the mediator from my store? Could I even use `@listenTo` in a mediator? Or do you think there is a better way to solve this problem? 

Thanks :)

**Comment by DominikGuzei** [comment]
Hey there,
you can just raise an error action in the store and `@listenTo` with the mediator. Since `Mediator` extends `Space.ui.Messenger` it can listen to any action in your system :wink: Then you just set a state property for your views which render the error message!

**Comment by zimt28** [comment]
That's good to know :D I think I'll just create one class that listens to all my notifications :) Can I also trigger events from a store? Have a nice weekend!

**Comment by DominikGuzei** [comment]
Yes you can, although it is not recommended by the flux architecture. Also, you can't dispatch another action while handling the current action. This is the basic rule of flux: Don't create nested runtime circles, because they will cause problems and can potentially lead to endless-loops. `space:ui` will throw an error at you when you try to dispatch an action while handling one :wink: 

Normally some part of the system (UI / http call / etc.) raises an action which is handled by one or multiple stores. These stores update their internal data, which is propagated to the views etc. Then the system is ready for the next action.

**Comment by npvn** [comment]
Hi @DominikGuzei, I'm getting familiar with space-ui. Love it so far!

I have the same problem as what @zimt28 mentioned: Inside a function in my store, I call a Meteor method. In case the method returns an error, I want to display notification to user.

As you pointed out, we should have the store tell the mediator about the error, and place the code to display notification inside the mediator.

However, it looks like `Space.ui.Messenger` has been removed in https://github.com/CodeAdventure/space-ui/commit/3e71a85cdc61f01e2be8716707785759e33193b4. 

How should I implement communication between store and mediator in this case?

**Comment by DominikGuzei** [comment]
Hey @npvn!
`Space.ui.Messenger` has been replaced by `Space.messaging.Controller` which provides the same capabilities but leverages the `space:messaging` package. So you can just send messages like this:

```coffeescript
class @TodosStore extends Space.ui.Store

  invokeServerMethod: -> Meteor.call 'yourMethod', (error, response) =>
    @eventBus.publish new SomethingInterestingHappened data: response
```

But in reality I think you should avoid this. This is were Meteor is actually better than React: Use reactivity to show notifications / errors to the user. So just setup a dedicated store for these messages or (which I actually like better) call the meteor method from within your mediator and handle errors directly where you need them.

**Comment by npvn** [comment]
@DominikGuzei: Thanks for your reply!

So we're having 3 possible approaches:
- Emit an event from inside the store to tell mediator about the error
- Call the Meteor method inside mediator
- Use an `ErrorsStore` and let Meteor's reactivity do the work 

I think option 1 is not recommended in the Flux architecture.

I don't like option 2, because my Meteor method contains the logic to update data. It's un-natural to call such a method inside mediator.

The final one looks like the best approach, since it fits perfectly with the Flux architecture!

**Comment by DominikGuzei** [comment]
Hey @npvn! Yeah I also think option 2 and 3 are the good ones :wink: Having a dedicated error store might be good if you want a more centralized error handling that is decoupled from specific components.

I like the mediator approach more because I don't simulate methods on the client anyway and it keeps the scope of functionality close together. Lately I tend to split up my application into folders per-feature with full-stack code of one functionality neatly packaged. This makes reasoning about data-flow and changing things much easier in my opinion.

**Comment by npvn** [comment]
Organizing the codebase into folders on a per-feature basic sounds interesting. I will experiment with this idea :+1:
