### ISSUE TITLE
Space.ui.Mediator not available

### ISSUE THREAD

**Issue by zimt28** [CodeAdventure/space-ui#12]
When I `meteor add space:ui` to an existing app and run it, there is no `Space.ui.Mediator` available. Where can I get it from?

**Comment by zimt28** [comment]
I'll try the latest version tomorrow and then let you know if it works!

**Comment by DominikGuzei** [comment]
cool thanks!

**Comment by zimt28** [comment]
Will take some more time as [martino:iron-router-i18n](https://github.com/yoolab/iron-router-i18n) doesn't support iron:router 1 yet and I don't get the latest version of space:ui because of that /:

**Comment by DominikGuzei** [comment]
@zimt28 please try it with version 3.4.0 – I removed iron-router support and with it the dependency on any specific iron-router version. Since the RouterController API wasn't very useful anyway this makes more sense. Please have a look at the TodoMVC example to see how `iron:router` is integrated by the application now.

**Comment by zimt28** [comment]
Nice :) Just ported my first page to space:ui, great work :+1:

**Comment by DominikGuzei** [comment]
Awesome! Glad it works for you now :-)

**Comment by zimt28** [comment]
Yeah, thanks :) How would you get a single document from the store?

**Comment by DominikGuzei** [comment]
You can put anything into the `state` of the store, also a the cursor to a single document:
```CoffeeScript
setInitialState: -> {
    firstTodo: @todos.findOne() # 
}
```
and change it later to anything else in any of the store methods:
```CoffeeScript
setState 'firstTodo', title: 'blablub' 
```
