### ISSUE TITLE
Mediator vs. Controller

### ISSUE THREAD

**Issue by DerMambo** [CodeAdventure/space-ui#16]
Hi @DominikGuzei,

after using space-ui and getting into it I really like it and am willing to use it, great job so far!

One thing I am looking at right now is the Mediator and I have some suggestions/questions/discussing points for that.

Why not use one single Mediator for the whole app that is only for the communication between different parts of the application. You might want to look at ChaplinJS which has a very good implementation of the mediator pattern (http://chaplinjs.org/) and modular application design in general.

This way you could take the responsibility for e.g. helpers out of the mediator but put it into controllers or introduce a new component class that is responsible for the orchestration of templates. Maybe one could also use the iron-router controller which provides this kind of functionality?!

Keep up the good work!
Manuel

**Comment by DerMambo** [comment]
After some rethinking... Ary you already doing exactly this?

I would say your Mediator already is the Component but the @actions method is what triggers the single Mediator.

Maybe it would even be sufficient to rename the Mediator to Component?
And then inside of the Component you would have s.th. like 

    @mediator.publish('eventName', {some: data});

**Comment by DominikGuzei** [comment]
Hey there, I am on holidays until Sunday - i will answer next week :wink:

**Comment by DerMambo** [comment]
Yes I know, it is more a reminder for our call ;)

**Comment by DominikGuzei** [comment]
Hey @DerMambo, I am back in town re-united with my Laptop after a great holiday trip to Budapest :wink:

Ok let me explain how `space:ui` works in Chaplin terms:

1. **Application:** This is your [Space.Application](https://github.com/CodeAdventure/meteor-space#2-control-over-configuration-and-initialization) that is responsible to map, configure and initialize everything that exists in your whole app. Without it, nothing would be instantiated or mapped into the dependency injection system. 
2. **Router / Layout:** You can use any package you want, it only has to use the standard Meteor Blaze templates for rendering. Currently I am using `iron:router` for that purpose, but `space:ui` has no dependency on it.
3. **Dispatcher / Controller:** There is no concept of "screen" or "one controller per screen" in `space:ui` since it follows the philosophy of [React.js](http://facebook.github.io/react/) and [Flow](http://facebook.github.io/flux/docs/overview.html). That means that there are dumb, composable `views` (in our case these are plain Meteor templates) and for some (higher-level) regions there are `mediators` that know how to provide data to their managed views.
4. **Models / Views:** There are no models and views in the classic sense. The only place where data is manipulated and prepared for the rest of the app are `stores`. The views are just simple meteor templates that get their data from some mediator (but don't know that – they just access the data over some variable like `state`)

**Comment by DominikGuzei** [comment]
To clarify your confusion about `@actions`:
There is exactly one `Dispatcher` for your whole application which works like a simple event bus. So you could get a reference to that anywhere by declaring `dispatcher: 'Space.ui.Dispatcher'` as a dependency. Then you can broadcast an action by calling `@dispatcher.dispatch` with a plain object. There is no filtering system or anything, it just gets broadcasted to any listener in your app – They can decide if they are interested in the action by looking on the payload object. The reason for this is simple: There are not many listeners, most commonly there are only a few stores that react to actions. All other parts of you application (e.g. `mediators` / `views`) are updated "magically" via the Meteor reactive `Tracker`. So your mediators / views dont need to listen to these actions (and they shouldn't have to).

**Comment by DerMambo** [comment]
Thx by the way! :)

**Comment by DominikGuzei** [comment]
You are welcome :wink:
