### ISSUE TITLE
Space UI is hard to debug

### ISSUE THREAD

**Issue by fr0zen** [CodeAdventure/space-ui#31]
Hi @DominikGuzei! I've been using Space UI for the last weeks and it is very nice. But very hard to debug. 
For example, when a class defined in client.coffee don't exists or has some typo/error, no error message is sent. I'm going to look more about it, but I wanted to create the issue before to know if this subject was already discussed here or you have some good ideas about the reasons. Thanks Dominik!
 
Links:
https://github.com/fr0zen/SpaceUI-TodoMVC
http://spaceui-todomvc.meteor.com

**Comment by DominikGuzei** [comment]
Hey @fr0zen!
Thanks for the feedback, you're totally right – the Space framework currently has its weaknesses in regard to debugging. As the problem also bites me regularly i am already working on some solutions and will introduce better error messages / stricter checks in the coming days!

Let's keep this thread open for discussion, so that we can exchange concrete examples where improvements are needed! One of the first things that i will do now, is to add a feature to the class system so that you can provide a full namespace and the classes are correctly displayed in the debugging consoles instead of the annoying `_Class` shit that is happening because of coffeescript right now.

Could you elaborate more on your example? Maybe a short code snippet with comments would be great, i didn't completely get what you mean with a class defined in `client.coffee` :wink:

**Comment by fr0zen** [comment]
Great, @DominikGuzei!
I saw here that I forgot to push the code. Look at this file:
https://github.com/fr0zen/SpaceUI-TodoMVC/blob/master/client/client.coffee

I intentionally changed the name of InputComponent to InputsComponent to test. It doesn't break, only show a blank page, as you can see in: http://spaceui-todomvc.meteor.com

**Comment by DominikGuzei** [comment]
Hey @fr0zen,
Please try out version 5.1.3 – (add `space:ui@5.1.3` in `.meteor/packages`), i added a better error message for this case, when a blaze component could not be located :wink:

**Comment by fr0zen** [comment]
Hey @DominikGuzei! Awesome! Do the others dependencies (controllers, mediators and all) also need this "error handling"?

**Comment by DominikGuzei** [comment]
Yeah, i will work on those too – although there are different places these have to be handled. I will keep you updated when the error messages are improved :wink:

**Comment by DominikGuzei** [comment]
Hey @fr0zen, you can now update to `space:ui@5.2.0` which covers all the little debugging problems.

**Comment by fr0zen** [comment]
Thanks, @DominikGuzei! I'll keep using space-ui and hope to contribute with it. Great job you're doing. I'm having a great time integrating space-ui with OrionJS :) Very productive.

**Comment by DominikGuzei** [comment]
You're welcome, thanks for the important feedback! There is still a lot to improve, but I agree it is already very productive and i love how the space framework gives projects a structural guidance. When you have seen one space app you will feel at home in any other, which is something that Meteor is lacking IMO.

Btw. I started to setup a little bit more complex application written in Javascript, using all the latest APIs and improvements: https://github.com/SpaceJs/cqrs-shop-example It is just the beginning, nothing to see yet but you can follow the updates to get a feeling how to build a larger scale space project :wink:
